spring.application.name=BG
server.port=${APP_PORT:8086}

#Configuración del docker secrets
spring.config.import=optional:configtree:/run/secrets/

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
spring.datasource.username=${db_user:postgres}
spring.datasource.password=${db_password:password}
# ----------------------------------------------

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update